///|
pub fn echo_ints(v : Array[Int]) -> Array[Int] { v }
///|
pub fn echo_doubles(v : Array[Double]) -> Array[Double] { v }
///|
pub fn echo_bools(v : Array[Bool]) -> Array[Bool] { v }
///|
pub fn echo_strings(v : Array[String]) -> Array[String] { v }
///|
pub fn echo_binary(v : Array[Bytes]) -> Array[Bytes] { v }
///|
pub fn echo_nested(v : Array[Array[String]]) -> Array[Array[String]] { v }
///|
pub fn join_ints(a : Array[Int], b : Array[Int]) -> Array[Int] { a + b }
